---
- name: Install Git on EC2 instances
  hosts: all
  remote_user: ec2-user
  become: yes

  tasks:
    - name: Update apt/yum package cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Git
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Git
      dnf:
        name: git
        state: present
      when: ansible_os_family == "Amazon Linux"


    - name: Install Git
      dnf:
        name: git
        state: present
      when: ansible_os_family == "RedHat"
...
